Dsn = "root:example@/radsec?charset=utf8mb4,utf8"
ControlListen="127.0.0.1:8124"

[listen]
	[listen.auth]
		Addr="0.0.0.0:1812"
		Secret="secret"
		CIDR=["0.0.0.0/0"]
	[listen.acct]
		Addr="0.0.0.0:1813"
		Secret="secret"
		CIDR=["0.0.0.0/0"]